### ISSUE TITLE
Parallel-testing needs to be moved

### ISSUE THREAD

**Issue by nadvolod** [saucelabs-training/demo-java#99]
https://github.com/saucelabs-training/demo-java/tree/master/parallel-testing needs to be moved to the right place. It looks like it's showing off cross-browser parallelization with TestNg in multiple ways. My assumption is that it just needs to be moved into `selenium-testng-examples`. It's going here because it's specific to a testing library and likely requires a special pom.xml or another xml?

**Comment by c3ccl3ston** [comment]
@nadvolod - question on this... both the cross-browser-and-platform-config and single-browser-config packages have exactly the same items (pages and tests), should I try to refactor the code so that it is a very simple example (a single class), in both cases, somewhat like your TestNgTest that is in the selenium-testng-examples folder already?

**Comment by nadvolod** [comment]
@c3ccl3ston that's an excellent suggestion! Historically, the thing that kills us with these repositories is the maintenance aspect. Anything we can do to minimize that, such as removing page objects, is probably a smart move
